### ISSUE TITLE
Фидбэк

### ISSUE THREAD

**Issue by TheZavitaev** [catstyle1101/datafort#1]
Привет! 
Если не против, напишу сюда, так как разметка работает :) 

#### Хорошо: 
1) Есть логи
2) Есть обработка исключений
3) Неплохое ридми
4) ООП, с абстрактными классами (хоть и выглядит оверхедом для задачи).
5) Используешь паттерн репозиторий
6) Докстринги
7) Пайдентик
8) Используешь валидные классы исключений

#### Плохо: 
1) Не обрабатываешь невалидные ответы API (4хх, 5хх ошибки)
2) Записываешь города поштучно, а значит держись сессию открытой дольше положенного (используй загрузку чанками)
3) Города в пайтон файле, изменение этого списка потребует пересборки контейнера, что не всегда удобно. В целом, нормально для первичного наполнения, но это было бы лучше сделать через API или через файл (csv, sql).

#### Можно лучше: 
1) Использовать актуальную версию постгрес. SQLite не подходит для прода и с неё не всегда так просто перейти.
2) В качестве технологических ограничений и проблем можно было бы указать ограничения со стороны API (в частности - `Calls per minute: 60` и `1,000,000 calls/month`, а значит, когда городов станет больше 1388, нужно будет в любом случае покупать подписку иначе мы упремся в ограничения со стороны API).
3) Было бы неплохо добавить ретраи, загляни [сюда](https://stackoverflow.com/a/35504626)
4) Селери, на мой взгляд тяжеловат для этой задачи. Можно было бы использовать `APScheduler`. Он полегче, и более прост в настройке.

#### Общее впечатление и рекомендации: 
В проде у подобных коллекторов мы используем ABC, но по той причине, что у нас коллекторов много, а структуру нужно повторять для каждого. Поэтому в нашем случае использование этой штуки рационально. Когда мы говорим об одном коллекторе, но это выглядит как стрельба по воробьям из пушки).

Насколько я вижу по твоему репозиторию, с этим API ты уже работал, поэтому хотелось бы здесь увидеть именно работу с "узкими" местами (статус, коды, try/except), а также возможности развития сервиса.

К сожалению, я не готов пригласить тебя на интервью, надеюсь, что этот фидбэк поможет тебе с развитием и получением оффера :)

**Comment by catstyle1101** [comment]
Привет! Спасибо за фидбек.

- Добавил PostgreSQL
- Добавил проверку 4хх и 5хх ответов сервера
- Исправил первичную заливку базы - теперь через csv заливается.
- Добавил ретраи при запросах.
- Добавил запись погоды чанками (размер чанка можно настроить в config.py)
- Исправил ограничения в README.md
